// <auto-generated />
using System;
using DreamJourney.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamJourney.Migrations
{
    [DbContext(typeof(DreamJourneyDbContext))]
    partial class DreamJourneyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamJourney.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Градски турове"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Културни екскурзии"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "Морски почивки"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Планински почивки"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Name = "Екстремни"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Name = "Еко туризъм"
                        });
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Екскурзии"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Почивки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Приключения"
                        });
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureCategoryId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeatureCategoryId = 1,
                            Name = "Самолет"
                        },
                        new
                        {
                            Id = 2,
                            FeatureCategoryId = 1,
                            Name = "Автобус"
                        },
                        new
                        {
                            Id = 3,
                            FeatureCategoryId = 2,
                            Name = "Хотел 2*"
                        },
                        new
                        {
                            Id = 4,
                            FeatureCategoryId = 2,
                            Name = "Хотел 3*"
                        },
                        new
                        {
                            Id = 5,
                            FeatureCategoryId = 2,
                            Name = "Хотел 4*"
                        },
                        new
                        {
                            Id = 6,
                            FeatureCategoryId = 2,
                            Name = "Хотел 5*"
                        },
                        new
                        {
                            Id = 7,
                            FeatureCategoryId = 3,
                            Name = "Закуска"
                        },
                        new
                        {
                            Id = 8,
                            FeatureCategoryId = 3,
                            Name = "HB"
                        },
                        new
                        {
                            Id = 9,
                            FeatureCategoryId = 3,
                            Name = "FB"
                        },
                        new
                        {
                            Id = 10,
                            FeatureCategoryId = 3,
                            Name = "All Inclusive"
                        },
                        new
                        {
                            Id = 11,
                            FeatureCategoryId = 4,
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 12,
                            FeatureCategoryId = 4,
                            Name = "Трансфер"
                        },
                        new
                        {
                            Id = 13,
                            FeatureCategoryId = 4,
                            Name = "Басейн"
                        },
                        new
                        {
                            Id = 14,
                            FeatureCategoryId = 4,
                            Name = "Аквапарк"
                        },
                        new
                        {
                            Id = 15,
                            FeatureCategoryId = 4,
                            Name = "Фитнес"
                        },
                        new
                        {
                            Id = 16,
                            FeatureCategoryId = 4,
                            Name = "СПА"
                        });
                });

            modelBuilder.Entity("DreamJourney.Data.Models.FeatureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SingleSelection")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FeatureCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Транспорт",
                            SingleSelection = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Хотел",
                            SingleSelection = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Хранене",
                            SingleSelection = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Екстри",
                            SingleSelection = false
                        });
                });

            modelBuilder.Entity("DreamJourney.Data.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Уикенд"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Седмични"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Исторически"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Музеи"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Лято"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Name = "Зима"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            Name = "Рафтинг"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 6,
                            Name = "Пешеходни"
                        });
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinations")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FromPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.TripApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("TripApplications");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.TripFeature", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("TripId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("TripFeatures");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("Role")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Category", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.Department", "Department")
                        .WithMany("Categories")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Feature", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.FeatureCategory", "FeatureCategory")
                        .WithMany("Features")
                        .HasForeignKey("FeatureCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureCategory");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.SubCategory", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Trip", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamJourney.Data.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamJourney.Data.Models.SubCategory", "SubCategory")
                        .WithMany("Trips")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DreamJourney.Data.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.TripApplication", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.Trip", "Trip")
                        .WithMany("TripApplications")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamJourney.Data.Models.User", "User")
                        .WithMany("TripApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.TripFeature", b =>
                {
                    b.HasOne("DreamJourney.Data.Models.Feature", "Feature")
                        .WithMany("TripFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamJourney.Data.Models.Trip", "Trip")
                        .WithMany("TripFeatures")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Department", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Feature", b =>
                {
                    b.Navigation("TripFeatures");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.FeatureCategory", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.SubCategory", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.Trip", b =>
                {
                    b.Navigation("TripApplications");

                    b.Navigation("TripFeatures");
                });

            modelBuilder.Entity("DreamJourney.Data.Models.User", b =>
                {
                    b.Navigation("TripApplications");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
